const META={vix:['VIX 恐慌指數','', 'Yahoo Finance / CBOE'],putCall:['Put/Call Ratio','', 'CBOE'],marginMaintenance:['台灣融資維持率','%','市場估算'],foreignFutures:['外資台指期淨部位',' 口','TAIFEX'],dxy:['美元指數 DXY','','Yahoo Finance'],usdtwd:['USD/TWD','','Yahoo Finance'],gold:['黃金期貨','', 'Yahoo Finance'],us2y:['美債 2Y','%','U.S. Treasury'],us10y:['美債 10Y','%','Yahoo Finance'],us30y:['美債 30Y','%','Yahoo Finance'],wti:['WTI 原油','$','Yahoo Finance']};
const WORKER_URL='https://market-risk-dashboard-api.tim800830.workers.dev/';
let history=[],selected='marginMaintenance',range=7,arkRange=7,chart,arkChart,lastUpdatedAt=null,arkDisplayedValue=0,arkAnimation=null;
const fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('zh-TW',{maximumFractionDigits:d,minimumFractionDigits:d}):'待資料';
function latestPoint(key){for(let i=history.length-1;i>=0;i--){const v=history[i].values?.[key];if(Number.isFinite(v))return {date:history[i].date,value:v};}return null;}
function pointsFor(key){return history.map(x=>({date:x.date,value:x.values?.[key]})).filter(x=>Number.isFinite(x.value));}
function comparison(key){const p=pointsFor(key);if(p.length<2)return null;return {d:p.at(-1).value-p.at(-2).value};}
function render(){const cards=document.querySelector('#cards');cards.innerHTML='';let up=0,down=0,flat=0,available=0;Object.entries(META).forEach(([key,[name,suffix,source]])=>{const latest=latestPoint(key),val=latest?.value,c=comparison(key);if(Number.isFinite(val))available++;let cls='na',label='尚無前日資料';if(c){if(Math.abs(c.d)<1e-10){flat++;cls='flat';label='→ 持平';}else if(c.d>0){up++;cls='up';label=`↑ ${fmt(Math.abs(c.d))}`;}else{down++;cls='down';label=`↓ ${fmt(Math.abs(c.d))}`;}}const el=document.createElement('article');el.className='card'+(selected===key?' selected':'');const stale=latest&&latest.date!==history.at(-1)?.date?`<span class="source">資料日 ${latest.date.slice(5).replace('-','/')}</span>`:'';el.innerHTML=`<div class="card-top"><h3>${name}</h3><span class="source">${source}</span></div><div class="value ${Number.isFinite(val)?'':'na'}">${fmt(val)}${Number.isFinite(val)?suffix:''}</div><div class="delta ${cls}">${label}</div>${stale}`;el.onclick=()=>{selected=key;render();drawChart()};cards.appendChild(el)});availableCount.textContent=available;upCount.textContent=up;downCount.textContent=down;flatCount.textContent=flat;drawChart();}
function drawChart(){if(!window.Chart)return setTimeout(drawChart,100);const [name,suffix]=META[selected],all=pointsFor(selected),p=range==='all'?all:all.slice(-Number(range));chartTitle.textContent=name;if(chart)chart.destroy();chart=new Chart(document.querySelector('#historyChart'),{type:'line',data:{labels:p.map(x=>x.date),datasets:[{label:name,data:p.map(x=>x.value),borderWidth:2,tension:.25,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${fmt(c.raw)}${suffix}`}}},scales:{x:{grid:{display:false}},y:{grid:{color:'rgba(145,164,191,.12)'}}}}});}
function arkPoints(){return pointsFor('arkRisk');}
function drawArkChart(){const panel=document.querySelector('#arkHistoryPanel');if(!panel||panel.hidden||!window.Chart)return;if(arkChart)arkChart.destroy();const all=arkPoints(),p=arkRange==='all'?all:all.slice(-Number(arkRange));arkChart=new Chart(document.querySelector('#arkHistoryChart'),{type:'line',data:{labels:p.map(x=>x.date),datasets:[{data:p.map(x=>x.value),borderWidth:3,tension:.3,pointRadius:4,fill:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`方舟 ${fmt(c.raw,1)}%`}}},scales:{x:{grid:{display:false}},y:{suggestedMin:0,suggestedMax:100,ticks:{callback:v=>v+'%'},grid:{color:'rgba(145,164,191,.12)'}}}}});}
function paintArk(value){const v=Math.max(0,Math.min(100,value));arkGauge?.style.setProperty('--risk',v);if(arkGaugeValue)arkGaugeValue.textContent=`${fmt(v,1)}%`;arkDisplayedValue=v;}
function animateArk(target,fromZero=false){const end=Math.max(0,Math.min(100,target));if(arkAnimation)cancelAnimationFrame(arkAnimation);const start=fromZero?0:arkDisplayedValue,duration=1100,startAt=performance.now();if(fromZero)paintArk(0);const tick=now=>{const t=Math.min(1,(now-startAt)/duration),e=1-Math.pow(1-t,3);paintArk(start+(end-start)*e);if(t<1)arkAnimation=requestAnimationFrame(tick);else{paintArk(end);arkGauge?.classList.remove('ark-pulse');void arkGauge?.offsetWidth;arkGauge?.classList.add('ark-pulse');}};arkAnimation=requestAnimationFrame(tick);}
function renderArk(animate=false){const p=arkPoints(),latest=p.at(-1);if(latest)animateArk(latest.value,!animate);else{arkGauge?.style.setProperty('--risk',0);arkGaugeValue.textContent='—';arkDisplayedValue=0;}const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}),todayPoint=p.find(x=>x.date===today);riskHistory.innerHTML=todayPoint?`<span>${todayPoint.date.slice(5).replace('-','/')}　<b>${fmt(todayPoint.value,1)}%</b></span>`:'<span class="na">今日尚未記錄</span>';drawArkChart();}
function setArkHistoryOpen(open){const panel=document.querySelector('#arkHistoryPanel'),btn=document.querySelector('#arkHistoryToggle');if(!panel||!btn)return;panel.hidden=!open;btn.classList.toggle('is-open',open);btn.setAttribute('aria-expanded',String(open));btn.querySelector('span').textContent=open?'⌃':'⌄';if(open)setTimeout(drawArkChart,30);}
function applyResponsiveDefaults(){const mobile=window.matchMedia('(max-width:560px)').matches;setArkHistoryOpen(!mobile);const allocation=document.querySelector('#allocationDetails');if(allocation)allocation.open=!mobile;}
function initResponsivePanels(){applyResponsiveDefaults();let wasMobile=window.matchMedia('(max-width:560px)').matches;window.addEventListener('resize',()=>{const mobile=window.matchMedia('(max-width:560px)').matches;if(mobile!==wasMobile){wasMobile=mobile;applyResponsiveDefaults();}});arkHistoryToggle?.addEventListener('click',()=>setArkHistoryOpen(arkHistoryToggle.getAttribute('aria-expanded')!=='true'));}
async function fetchHistory(){const r=await fetch(`data/history.json?${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`history HTTP ${r.status}`);return r.json();}
function applyHistory(d,animateArkGauge=false){history=d.records||[];lastUpdatedAt=d.updatedAt||null;updatedAt.textContent=lastUpdatedAt?new Date(lastUpdatedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'—';render();renderArk(animateArkGauge);}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
async function waitForUpdate(baseline,check){const started=Date.now();while(Date.now()-started<150000){await sleep(3000);const d=await fetchHistory();if(d.updatedAt&&d.updatedAt!==baseline&&(!check||check(d))){applyHistory(d,true);return d;}}throw new Error('等待 GitHub 更新逾時');}
riskForm.addEventListener('submit',async e=>{e.preventDefault();const value=Number(riskInput.value);if(!Number.isFinite(value)||value<0||value>100)return;const btn=riskForm.querySelector('button[type="submit"]'),baseline=lastUpdatedAt;btn.disabled=true;arkSaveStatus.textContent='正在儲存到 GitHub…';try{const r=await fetch(WORKER_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'saveArk',ark_value:String(value)})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(j.error||`Worker HTTP ${r.status}`);await waitForUpdate(baseline,d=>{const rec=d.records?.find(x=>x.date===new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}));return Number(rec?.values?.arkRisk)===value;});riskInput.value='';arkSaveStatus.textContent='✓ 已長期儲存，同日再次記錄會覆蓋';}catch(err){arkSaveStatus.textContent=`儲存失敗：${err.message}`;}finally{btn.disabled=false;}});
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-range]').forEach(x=>x.classList.remove('active'));b.classList.add('active');range=b.dataset.range;drawChart()});
document.querySelectorAll('[data-ark-range]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-ark-range]').forEach(x=>x.classList.remove('active'));b.classList.add('active');arkRange=b.dataset.arkRange;drawArkChart()});
function setLoading(show,text='正在更新市場資料…'){loadingText.textContent=text;loadingOverlay.classList.toggle('show',show);loadingOverlay.setAttribute('aria-hidden',show?'false':'true');}
function clickTime(){return new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false});}
async function refreshLatest(){const btn=refreshBtn,baseline=lastUpdatedAt;btn.disabled=true;btn.textContent='↻ 更新中…';refreshStatus.textContent=`手動更新：${clickTime()}`;setLoading(true,'正在啟動 GitHub Action…');try{const r=await fetch(WORKER_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(j.error||`Worker HTTP ${r.status}`);setLoading(true,'GitHub Action 已啟動，正在取得最新市場資料…');await waitForUpdate(baseline);refreshStatus.textContent=`手動更新完成：${clickTime()}`;setLoading(true,'最新市場資料已更新');await sleep(700);}catch(e){refreshStatus.textContent=`更新失敗：${e.message}`;setLoading(true,`更新失敗：${e.message}`);await sleep(1600);}finally{setLoading(false);btn.disabled=false;btn.textContent='↻ 更新最新數據';}}
refreshBtn?.addEventListener('click',refreshLatest);initResponsivePanels();fetchHistory().then(d=>applyHistory(d,false)).catch(()=>{render();renderArk(false);});