const META={vix:['VIX 恐慌指數','', 'Yahoo Finance / CBOE'],putCall:['Put/Call Ratio','', 'CBOE'],marginMaintenance:['台灣融資維持率','%','市場估算'],foreignFutures:['外資台指期淨部位',' 口','TAIFEX'],dxy:['美元指數 DXY','','Yahoo Finance'],usdtwd:['USD/TWD','','Yahoo Finance'],gold:['黃金期貨','', 'Yahoo Finance'],us2y:['美債 2Y','%','U.S. Treasury'],us10y:['美債 10Y','%','Yahoo Finance'],us30y:['美債 30Y','%','Yahoo Finance'],wti:['WTI 原油','$','Yahoo Finance']};
let history=[],selected='marginMaintenance',range=7,chart;
const fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('zh-TW',{maximumFractionDigits:d,minimumFractionDigits:d}):'待資料';
const latestValues=()=>history.length?history[history.length-1].values:{};
function pointsFor(key){return history.map(x=>({date:x.date,value:x.values?.[key]})).filter(x=>Number.isFinite(x.value));}
function comparison(key){const p=pointsFor(key);if(p.length<2)return null;const a=p.at(-1).value,b=p.at(-2).value,d=a-b;return {d,pct:b!==0?d/Math.abs(b)*100:null};}
function render(){const values=latestValues(),cards=document.querySelector('#cards');cards.innerHTML='';let up=0,down=0,flat=0,available=0;Object.entries(META).forEach(([key,[name,suffix,source]])=>{const val=values[key],c=comparison(key);if(Number.isFinite(val))available++;let cls='na',label='尚無前日資料';if(c){if(Math.abs(c.d)<1e-10){flat++;cls='flat';label='→ 持平';}else if(c.d>0){up++;cls='up';label=`↑ ${fmt(Math.abs(c.d))}`;}else{down++;cls='down';label=`↓ ${fmt(Math.abs(c.d))}`;}}const el=document.createElement('article');el.className='card'+(selected===key?' selected':'');el.innerHTML=`<div class="card-top"><h3>${name}</h3><span class="source">${source}</span></div><div class="value ${Number.isFinite(val)?'':'na'}">${fmt(val)}${Number.isFinite(val)?suffix:''}</div><div class="delta ${cls}">${label}</div>`;el.onclick=()=>{selected=key;render();drawChart()};cards.appendChild(el)});availableCount.textContent=available;upCount.textContent=up;downCount.textContent=down;flatCount.textContent=flat;drawChart();}
function drawChart(){if(!window.Chart)return setTimeout(drawChart,100);const [name,suffix]=META[selected],all=pointsFor(selected),p=range==='all'?all:all.slice(-Number(range));chartTitle.textContent=name;if(chart)chart.destroy();chart=new Chart(document.querySelector('#historyChart'),{type:'line',data:{labels:p.map(x=>x.date),datasets:[{label:name,data:p.map(x=>x.value),borderWidth:2,tension:.25,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${fmt(c.raw)}${suffix}`}}},scales:{x:{grid:{display:false}},y:{grid:{color:'rgba(145,164,191,.12)'}}}}});}
function renderManual(){const arr=JSON.parse(localStorage.getItem('arkRiskHistory')||'[]');riskHistory.innerHTML=arr.slice(-8).reverse().map(x=>`<span>${x.date}　<b>${fmt(x.value)}%</b></span>`).join('')||'<span class="na">尚未記錄</span>';}
riskForm.addEventListener('submit',e=>{e.preventDefault();const value=Number(riskInput.value);if(!Number.isFinite(value))return;const date=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});let arr=JSON.parse(localStorage.getItem('arkRiskHistory')||'[]');arr=arr.filter(x=>x.date!==date);arr.push({date,value});localStorage.setItem('arkRiskHistory',JSON.stringify(arr));riskInput.value='';renderManual();});
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-range]').forEach(x=>x.classList.remove('active'));b.classList.add('active');range=b.dataset.range;drawChart()});
fetch('data/history.json?'+Date.now()).then(r=>r.json()).then(d=>{history=d.records||[];updatedAt.textContent=d.updatedAt?new Date(d.updatedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}):'—';render();renderManual()}).catch(()=>{render();renderManual()});