const META={vix:['VIX 恐慌指數','', 'Yahoo Finance / CBOE'],putCall:['Put/Call Ratio','', 'CBOE'],marginMaintenance:['台灣融資維持率','%','市場估算'],foreignFutures:['外資台指期淨部位',' 口','TAIFEX'],dxy:['美元指數 DXY','','Yahoo Finance'],usdtwd:['USD/TWD','','Yahoo Finance'],gold:['黃金期貨','', 'Yahoo Finance'],us2y:['美債 2Y','%','U.S. Treasury'],us10y:['美債 10Y','%','Yahoo Finance'],us30y:['美債 30Y','%','Yahoo Finance'],wti:['WTI 原油','$','Yahoo Finance']};
const WORKER_URL='https://market-risk-dashboard-api.tim800830.workers.dev/';
let history=[],selected='marginMaintenance',range=7,chart,lastUpdatedAt=null;
const fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('zh-TW',{maximumFractionDigits:d,minimumFractionDigits:d}):'待資料';
function latestPoint(key){for(let i=history.length-1;i>=0;i--){const v=history[i].values?.[key];if(Number.isFinite(v))return {date:history[i].date,value:v};}return null;}
function pointsFor(key){return history.map(x=>({date:x.date,value:x.values?.[key]})).filter(x=>Number.isFinite(x.value));}
function comparison(key){const p=pointsFor(key);if(p.length<2)return null;const a=p.at(-1).value,b=p.at(-2).value,d=a-b;return {d,pct:b!==0?d/Math.abs(b)*100:null};}
function render(){const cards=document.querySelector('#cards');cards.innerHTML='';let up=0,down=0,flat=0,available=0;Object.entries(META).forEach(([key,[name,suffix,source]])=>{const latest=latestPoint(key),val=latest?.value,c=comparison(key);if(Number.isFinite(val))available++;let cls='na',label='尚無前日資料';if(c){if(Math.abs(c.d)<1e-10){flat++;cls='flat';label='→ 持平';}else if(c.d>0){up++;cls='up';label=`↑ ${fmt(Math.abs(c.d))}`;}else{down++;cls='down';label=`↓ ${fmt(Math.abs(c.d))}`;}}const el=document.createElement('article');el.className='card'+(selected===key?' selected':'');const stale=latest&&latest.date!==history.at(-1)?.date?`<span class="source">資料日 ${latest.date.slice(5).replace('-','/')}</span>`:'';el.innerHTML=`<div class="card-top"><h3>${name}</h3><span class="source">${source}</span></div><div class="value ${Number.isFinite(val)?'':'na'}">${fmt(val)}${Number.isFinite(val)?suffix:''}</div><div class="delta ${cls}">${label}</div>${stale}`;el.onclick=()=>{selected=key;render();drawChart()};cards.appendChild(el)});availableCount.textContent=available;upCount.textContent=up;downCount.textContent=down;flatCount.textContent=flat;drawChart();}
function drawChart(){if(!window.Chart)return setTimeout(drawChart,100);const [name,suffix]=META[selected],all=pointsFor(selected),p=range==='all'?all:all.slice(-Number(range));chartTitle.textContent=name;if(chart)chart.destroy();chart=new Chart(document.querySelector('#historyChart'),{type:'line',data:{labels:p.map(x=>x.date),datasets:[{label:name,data:p.map(x=>x.value),borderWidth:2,tension:.25,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${fmt(c.raw)}${suffix}`}}},scales:{x:{grid:{display:false}},y:{grid:{color:'rgba(145,164,191,.12)'}}}}});}
function todayTaipei(){return new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});}
function loadArkHistory(){const raw=JSON.parse(localStorage.getItem('arkRiskHistory')||'[]');const byDate=new Map();for(const item of raw){if(item?.date&&Number.isFinite(Number(item.value)))byDate.set(item.date,{date:item.date,value:Number(item.value)});}return [...byDate.values()].sort((a,b)=>a.date.localeCompare(b.date));}
function saveArkHistory(arr){localStorage.setItem('arkRiskHistory',JSON.stringify(arr));}
function renderManual(){const arr=loadArkHistory();riskHistory.innerHTML=arr.slice(-8).reverse().map(x=>`<span>${x.date}　<b>${fmt(x.value)}%</b></span>`).join('')||'<span class="na">尚未記錄</span>';}
riskForm.addEventListener('submit',e=>{e.preventDefault();const value=Number(riskInput.value);if(!Number.isFinite(value))return;const date=todayTaipei();const arr=loadArkHistory();const existing=arr.find(x=>x.date===date);if(existing)existing.value=value;else arr.push({date,value});arr.sort((a,b)=>a.date.localeCompare(b.date));saveArkHistory(arr);riskInput.value='';renderManual();});
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-range]').forEach(x=>x.classList.remove('active'));b.classList.add('active');range=b.dataset.range;drawChart()});
function setLoading(show,text='正在更新市場資料…'){const overlay=document.querySelector('#loadingOverlay');const label=document.querySelector('#loadingText');if(label)label.textContent=text;if(overlay){overlay.classList.toggle('show',show);overlay.setAttribute('aria-hidden',show?'false':'true');}}
function clickTime(){return new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false});}
function displayUpdatedAt(value){updatedAt.textContent=value?new Date(value).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'—';}
async function loadHistory(){const r=await fetch(`data/history.json?${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`history HTTP ${r.status}`);const d=await r.json();history=d.records||[];lastUpdatedAt=d.updatedAt||null;displayUpdatedAt(lastUpdatedAt);render();return d;}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
async function refreshLatest(){const btn=document.querySelector('#refreshBtn');const clickedAt=clickTime();const baseline=lastUpdatedAt;btn.disabled=true;btn.textContent='↻ 更新中…';refreshStatus.textContent=`手動更新：${clickedAt}`;setLoading(true,'正在啟動 GitHub Action…');try{const trigger=await fetch(WORKER_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:'market-risk-dashboard'})});let result={};try{result=await trigger.json();}catch{}if(!trigger.ok||result.ok===false)throw new Error(result.error||`Worker HTTP ${trigger.status}`);setLoading(true,'GitHub Action 已啟動，正在取得最新市場資料…');const started=Date.now(),timeout=150000;while(Date.now()-started<timeout){await sleep(3000);setLoading(true,`正在等待最新資料… ${Math.floor((Date.now()-started)/1000)} 秒`);try{const r=await fetch(`data/history.json?poll=${Date.now()}`,{cache:'no-store'});if(!r.ok)continue;const d=await r.json();if(d.updatedAt&&d.updatedAt!==baseline){history=d.records||[];lastUpdatedAt=d.updatedAt;displayUpdatedAt(lastUpdatedAt);render();refreshStatus.textContent=`手動更新完成：${clickTime()}`;setLoading(true,'最新市場資料已更新');await sleep(700);return;}}catch{}}throw new Error('等待更新逾時，GitHub Action 可能仍在執行');}catch(e){console.error('[refresh]',e);refreshStatus.textContent=`更新失敗：${e.message}`;setLoading(true,`更新失敗：${e.message}`);await sleep(1800);}finally{setLoading(false);btn.disabled=false;btn.textContent='↻ 更新最新數據';}}
document.querySelector('#refreshBtn')?.addEventListener('click',refreshLatest);
loadHistory().then(renderManual).catch(()=>{render();renderManual();});